export const ACTIONS = {
    SEEK: 'seek',
    SOURCE_URL: 'sourceUrl',
    GET_SOURCE_URL: 'getSourceUrl',
    FRAME_LOADED: 'frameLoaded',
    LOAD_BOOKMARK: 'loadBookmark',
    INDA_NO_VIDEO: 'indaNoVideo',
    VIDEA_NO_VIDEO: 'videaNoVideo',
    VIDEO_ONLY_ON_INDAVIDEO: 'videoOnlyOnIndavideo',
    IFRAME: {
        FRAME_LOADED: 'FrameLoaded',
        AUTO_NEXT_EPISODE: 'AutoNextEpisode',
        NEXT_EPISODE: 'NextEpisode',
        PREVIOUS_EPISODE: 'PreviousEpisode',
        CURRENT_TIME: 'CurrentTime',
        REPLACE_PLAYER: 'ReplacePlayer',
        TOGGLE_PLAY: 'TogglePlay',
        VOL_UP: 'VolUp',
        VOL_DOWN: 'VolDown',
        TOGGLE_MUTE: 'ToggleMute',
        TOGGLE_FULLSCREEN: 'ToggleFullscreen',
        SEEK: 'Seek',
        SEEK_TO: 'SeekTo',
        BACKWARD_SKIP: 'BackwardSkip',
        FORWARD_SKIP: 'ForwardSkip',
        GET_CURRENT_TIME: 'getCurrentTime',
        PLAYER_READY: 'PlayerReady',
        SEEK_PERCENTAGE: 'seekPercentage',
        GET_BOOKMARKS: 'getBookmarks',
        TOAST: 'Toast',
        PLAYER_REPLACED: 'PlayerReplaced',
        PLAYER_REPLACE_FAILED: 'PlayerReplaceFailed',
        TOGGLE_THEATRE_MODE: 'ToggleTheatreMode',
        TOKEN_EXPIRED: 'TokenExpired',
    },
    DOWNLOAD: 'download',
} as const
